name: Create Production Pull Request

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Pull Request Title"
        required: false
        default: "Release to Production"
      body:
        description: "Pull Request Description"
        required: false
        default: "Automated pull request to merge changes from main to production."

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository using actions/checkout@v4
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history for accurate branch references

      # Step 2: Check for existing pull requests from main to production
      - name: Check for Existing Pull Requests
        id: check_pr
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:main`,
              base: 'production',
            });

            if (pullRequests.length > 0) {
              core.setFailed(`An open pull request from 'main' to 'production' already exists: #${pullRequests[0].number} - ${pullRequests[0].title}`);
            } else {
              console.log('No existing pull requests from main to production.');
            }

      # Step 3: Create Pull Request (only runs if Step 2 succeeds)
      - name: Create Pull Request
        # Ensures this step runs only if previous steps succeeded
        if: success()
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: main
          target: production
          title: ${{ github.event.inputs.title }}
          body: ${{ github.event.inputs.body }}
