name: Push Main to Production

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures all branches and history are fetched

      # Step 2: Configure Git
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Merge main into production
      - name: Merge main into production
        run: |
          git checkout production
          git merge main

      # Step 4: Push the updated production branch
      - name: Push changes
        run: git push origin production
        env:
          # The GITHUB_TOKEN is automatically provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
